version: "3.3"

services:
  php:
    build: ./docker
    expose:
      - 9000
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./:/code
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
